/ekf_yaw_fusion:
  ros__parameters:
    auto_yaw_offset: true
    base_frame: base_link_ekf
    odom_frame: odom
    publish_path: true
    q_xy_base: 0.01
    q_xy_scale: 0.02
    q_yaw_base: 0.02
    q_yaw_scale: 0.05
    r_yaw: 0.12
    use_sim_time: true
    yaw_offset: -0.0926

