icp_mapper:
  ros__parameters:
    scan_topic: "/scan"
    odom_topic: "/odom_icp"
    map_topic: "/icp_map"
    map_frame: "odom"

    resolution: 0.05
    width_m: 40.0
    height_m: 40.0
    origin_x: -20.0
    origin_y: -20.0

    min_range: 0.20
    max_range: 8.0
    beam_step: 4

    lo_occ: 0.85
    lo_free: -0.40
    lo_min: -5.0
    lo_max: 5.0

    publish_every_n_scans: 2