/icp_odom:
  ros__parameters:
    alpha: 0.25
    child_frame: base_link_icp
    clear_path_on_reset: true
    downsample_step: 1
    ekf_topic: /odom_ekf
    fov_deg: 270.0
    gate_rot: 0.45
    gate_trans: 0.3
    icp_iters: 25
    iters_coarse: 12
    max_corr_dist: 0.28
    max_corr_large: 0.45
    max_dt_gap: 1.0
    max_range: 3.2
    min_inlier_ratio: 0.08
    min_inliers: 25
    min_range: 0.2
    odom_frame: odom
    out_odom_topic: /odom_icp
    out_path_topic: /path_icp
    path_max_len: 4000
    reject_reset_N: 20
    res_clip_rot: 0.2
    res_clip_trans: 0.08
    reset_on_time_jump: true
    rmse_max: 0.12
    scan_topic: /scan
    sync_tolerance: 1.0
    use_sim_time: true
    yaw_search_levels: 2
    yaw_search_step: 0.08

