/wheel_odom:
  ros__parameters:
    base_frame: base_link_wheel
    left_joint: wheel_left_joint
    odom_frame: odom
    publish_path: true
    right_joint: wheel_right_joint
    use_sim_time: true
    wheel_radius: 0.033
    wheel_separation: 0.16

